apiVersion: v1
kind: Service
metadata:
  name: saidemy-service
spec:
  selector:
    app: regapp       # should match with deployment-level label
  ports:
    - port: 80        # service port
      targetPort: 80  # container port
  type: LoadBalancer

